# Generated by Django 4.0.5 on 2022-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('fechaLlegada', models.DateField()),
                ('fechasFlexibles', models.BooleanField()),
                ('destinos', models.JSONField()),
                ('cantidadNoches', models.IntegerField()),
                ('adultos', models.IntegerField()),
                ('menores', models.IntegerField()),
                ('presupuesto', models.IntegerField()),
                ('nivelAlojamiento', models.CharField(max_length=10)),
                ('vuelosInternacionales', models.BooleanField()),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('contenido', models.CharField(max_length=500)),
            ],
        ),
    ]
